### ISSUE TITLE
W,A,S,D instead of E,S,D,F

### ISSUE THREAD

**Issue by mo8it** [qu1x/bevy_trackball#2]
`E,S,D,F` seem to me very unintuitive as default keyboard bindings. Why not `W,A,S,D` like in every game? 😅

To be honest, I found the other keyboard binding not much more intuitive, but I don't have suggestions for them 🙃

**Comment by n3vu0r** [comment]
I agree, the default bindings are weird 😁 `W,A,S,D` might be the better default, and maybe changed to the usual spectator view movements. I started with `I,J,K,L` as they are remapped to `↑←↓→` by some keyboards when pressing a certain meta key like `Mod`. I have the [UHK](https://ultimatehackingkeyboard.com/). Then I just chose `E,S,D,F` for the symmetry as most keyboards have bumps on `F` and `J`.

**Comment by n3vu0r** [comment]
The `m` key now toggles between `esdf`/`wasd` mappings in the examples. You can also instantiate the controller with [`TrackballController::map_wasd()`](https://qu1x.github.io/bevy_trackball/doc/bevy_trackball/struct.TrackballController.html#method.map_wasd). Default is still `esdf` because I didn't want to redo the input mappings table in the docs 😅 (`esdf` slides on the focus plane like two-finger touch or right mouse button does. `wasd` leaves the focus plane instead.)

**Comment by mo8it** [comment]
Nice :D
